### ISSUE TITLE
Register on aiida plugin registry

### ISSUE THREAD

**Issue by ltalirz** [microsoft/aiida-dynamic-workflows#2]
Traditionally, this has been done via the `setup.json` but perhaps it makes sense to wait until @chrisjsewell has added support for the `setup.cfg`

Instructions on https://github.com/aiidateam/aiida-registry

**Comment by ltalirz** [comment]
Thanks to @chrisjsewell the feature to parse the `setup.cfg` has landed in the aiida registry.

@jbweston Would you be open to move the metadata from the `setup.py` into the `setup.cfg`?
You will need to drop the templating of the plugin name, but on the bright side you can rid of the code for dealing with package version synchronization.

See [example](https://github.com/aiidateam/aiida-firecrest/blob/main/setup.cfg)

**Comment by jbweston** [comment]
@ltalirz back to you 🎾 : #5 and https://github.com/aiidateam/aiida-registry/pull/195

**Comment by jbweston** [comment]
#5 is merged, just waiting on aiidateam/aiida-registry#195 now

**Comment by ltalirz** [comment]
Cheers, done!
